### ISSUE TITLE
No validation/ proper error message for image quality..

### ISSUE THREAD

**Issue by Vignesh-PS** [siva7170/Image-Manipulation-Library#1]
There is no proper validation/error message for image quality. Actually, i accidentally used image quality as 100 in PNG files. After that i debug manually and find, in the documentation of "Image quality of PNG files should be 0 to 9". So please fix this on your next commit. 

Thank you..!

**Comment by siva7170** [comment]
Hi Vignesh-PS, we will fix this issue and will update soon   Thank you for using image library :)

**Comment by siva7170** [comment]
Thank you @Vignesh-PS  We have fixed this issue on latest update. Please pull or use latest update.
Thank you for using our ImageManipulationLibrary
