### ISSUE TITLE
Transparent option not working in PNG files

### ISSUE THREAD

**Issue by Vignesh-PS** [siva7170/Image-Manipulation-Library#2]
I'd choose fit image option also ImagePreserverTransparent option enable too.. but output image is not fully transparent. 
The extra space is filled with black. Does it supports fully image with transparensive..?
For example, i've choose rectangle image, needed output image is square.
![privacy](https://user-images.githubusercontent.com/42610800/85825998-4bf22700-b7a1-11ea-9600-fbaa9614529e.png)

Kindly fix this..

Thank you..!

**Comment by siva7170** [comment]
Thank you @Vignesh-PS  We have fixed this issue on latest update. Please pull or use latest update.
Thank you for using our ImageManipulationLibrary
